import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'core/services/service_locator.dart';
import 'features/auth/logic/auth_bloc.dart';
import 'router/app_router.dart';
import 'firebase_options.dart'; // This file is generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // TODO: Run flutterfire configure to generate firebase_options.dart
  // For now, we'll wrap in a try-catch or comment it out until config is ready.
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  
  // Initialize dependency injection
  await setupServiceLocator();

  runApp(const PartyPlannerApp());
}

class PartyPlannerApp extends StatelessWidget {
  const PartyPlannerApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Create global AuthBloc
    final authBloc = AuthBloc(authRepository: getIt<AuthRepository>()); // Ensure generic type is inferred or import AuthRepository
    
    // Create Router with AuthBloc dependency
    final appRouter = AppRouter(authBloc);

    return BlocProvider(
      create: (context) => authBloc..add(AppStarted()),
      child: MaterialApp.router(
        title: 'PartyPlanner',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        routerConfig: appRouter.router,
      ),
    );
  }
}
